import { Colors, Radius, Spacing } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: Spacing.md },
  scroll: { paddingBottom: Spacing.xxxl },

  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: Spacing.xl, gap: Spacing.md },
  emptyIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: Colors.accentSoft,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: { marginTop: Spacing.sm },
  emptyBody: { textAlign: 'center', maxWidth: 320, lineHeight: 23 },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    minHeight: 52,
    backgroundColor: Colors.accent,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: Spacing.xl,
    paddingVertical: 14,
    borderRadius: 6,
    marginTop: Spacing.sm,
  },
  demoLink: { paddingVertical: Spacing.sm },
  retryBtn: { paddingVertical: Spacing.sm, paddingHorizontal: Spacing.lg },

  demoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 6,
    backgroundColor: Colors.warning + '14',
  },
  balanceCard: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.xl,
    paddingBottom: Spacing.lg,
  },
  balanceLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  portfolioTitle: { fontSize: 25, lineHeight: 31, fontWeight: '600' },
  overviewActions: { flexDirection: 'row', alignItems: 'center', gap: 23 },
  accountAddress: { marginTop: 5 },
  equityLabel: { marginTop: 24 },
  equity: { fontSize: 36, lineHeight: 43, fontWeight: '500', marginTop: 5 },
  overviewMetrics: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 21, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: Colors.border },
  overviewMetric: { width: '50%', minHeight: 60, paddingTop: 11, paddingRight: 10, paddingBottom: 5, gap: 4 },
  accountDetails: { marginHorizontal: Spacing.lg, marginTop: 12 },
  overviewValue: { fontSize: 19, lineHeight: 24, fontWeight: '500' },
  overviewNote: { fontSize: 10, lineHeight: 14 },
  coverageNote: { marginTop: 7, fontSize: 10, lineHeight: 15 },
  ledgerRow: { minHeight: 74, paddingHorizontal: Spacing.lg, paddingVertical: 13, flexDirection: 'row', gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: Colors.border },
  ledgerCopy: { flex: 1, gap: 5 },
  ledgerValue: { alignItems: 'flex-end', justifyContent: 'center', gap: 5 },
  ledgerNote: { marginHorizontal: Spacing.lg, marginBottom: 8, lineHeight: 16 },
  pnlRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 6 },

  riskCard: { marginHorizontal: Spacing.lg, marginTop: 18, paddingVertical: 14, gap: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: Colors.border },
  riskHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  riskTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  maintenanceBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(255,255,255,0.055)',
  },
  maintenanceBadgeWarning: { backgroundColor: Colors.warning + '14' },
  maintenanceBadgeUrgent: { backgroundColor: Colors.down + '16' },
  riskMetrics: {
    flexDirection: 'row',
    gap: 2,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.025)',
  },
  riskMetric: {
    flex: 1,
    minWidth: 0,
    minHeight: 64,
    justifyContent: 'center',
    paddingHorizontal: 9,
    paddingVertical: 3,
    backgroundColor: 'transparent',
    gap: 3,
  },
  riskMetricValue: { fontSize: 16, lineHeight: 20, fontWeight: '600' },
  riskWarning: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    borderRadius: Radius.sm,
    backgroundColor: Colors.warning + '0F',
  },
  riskWarningUrgent: { backgroundColor: Colors.down + '12' },
  riskWarningText: { flex: 1 },

  tabBarWrap: { marginTop: 20, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: Colors.border },
  tabBar: {
    flexDirection: 'row',
    gap: 0,
    padding: 4,
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 13,
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabActive: { borderBottomColor: Colors.accent },
  tabCount: {
    minWidth: 20,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
  },
  tabCountActive: { backgroundColor: Colors.accentSoft },
  noPositions: { padding: Spacing.xl, alignItems: 'center' },

  historyList: { paddingTop: Spacing.sm, gap: Spacing.sm },
  readStatus: {
    minHeight: 38,
    marginHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  historyState: {
    minHeight: 190,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.xl,
  },
  historyEmptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.045)',
    marginBottom: Spacing.xs,
  },
  historyEmptyDetail: { maxWidth: 300, textAlign: 'center', lineHeight: 16 },
  historyIntro: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginHorizontal: Spacing.lg,
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  historyIntroIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.accentSoft,
  },
  historyIntroCopy: { flex: 1, gap: 2 },
  historyCard: {
    marginHorizontal: Spacing.lg,
    padding: 14,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.075)',
    backgroundColor: Colors.surface,
    gap: Spacing.md,
  },
  historyCardTop: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.md },
  historyMarket: { flex: 1, minWidth: 0, gap: 4 },
  historyTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  historySymbol: { color: Colors.text, fontSize: 17, lineHeight: 21, fontWeight: '600' },
  historySideBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  historyPayment: { flex: 1.2, minWidth: 0, alignItems: 'flex-end', gap: 3 },
  historyPaymentValue: { fontSize: 15, lineHeight: 20, fontWeight: '600' },
  historyMetaRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingTop: Spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors.border,
  },
  historyMetaCell: { flex: 1, minWidth: 0, gap: 3 },
  historyMetaRight: { alignItems: 'flex-end' },
  interestHead: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  interestAssetIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  interestAssetCopy: { flex: 1, gap: 3 },
  interestValues: {
    flexDirection: 'row',
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.035)',
    paddingVertical: Spacing.sm,
  },
  interestValueCell: { flex: 1, alignItems: 'center', gap: 2 },
  interestValueDivider: { width: StyleSheet.hairlineWidth, backgroundColor: Colors.border },
  interestValue: { fontSize: 16, lineHeight: 21, fontWeight: '600' },

  // Rows mirror the main watchlist (SymbolRow): full-width hairline, logo 40,
  // 16/700 symbol, 16/600 value, 13px muted sub.
  list: {},
  positionCard: {
    marginHorizontal: Spacing.lg,
    marginTop: 12,
    borderRadius: 8,
    backgroundColor: Colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.border,
  },
  positionBody: { padding: 13, gap: 16 },
  positionDetails: { gap: Spacing.lg },
  positionSummary: { minHeight: 58 },
  positionSummaryTapTarget: { flexDirection: 'row', gap: 10, minHeight: 58 },
  positionSummaryPressed: {
    opacity: 0.78,
  },
  positionSummaryCell: { flex: 1, minWidth: 0, justifyContent: 'flex-start', gap: 7 },
  positionMarketCell: { flex: 1.05 },
  positionPnlCell: { flex: 1.25, paddingRight: 34 },
  positionColumnLabel: {
    color: Colors.textMuted,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
    letterSpacing: 0.65,
    textTransform: 'uppercase',
  },
  marketValueRow: { flexDirection: 'row', alignItems: 'center', gap: 5, minHeight: 32 },
  positionSymbol: { flexShrink: 0, fontSize: 20, lineHeight: 25, fontWeight: '600' },
  positionLeverageBadge: {
    flexShrink: 0,
    minWidth: 25,
    alignItems: 'center',
    paddingHorizontal: 5,
    paddingVertical: 3,
    borderRadius: 6,
  },
  positionLeverageText: { fontSize: 12, lineHeight: 15, fontWeight: '600' },
  positionPrimaryValue: { fontSize: 18, lineHeight: 24, fontWeight: '600' },
  pnlValueRow: { flexDirection: 'row', alignItems: 'center', gap: 6, minHeight: 32 },
  positionPnlText: { flex: 1, minWidth: 0, gap: 1 },
  positionPnlAmount: { fontSize: 18, lineHeight: 21, fontWeight: '600' },
  positionRoeText: { fontSize: 12, lineHeight: 15, fontWeight: '600' },
  positionChartButton: {
    position: 'absolute',
    top: 22,
    right: 0,
    width: 28,
    height: 28,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.border,
    backgroundColor: Colors.accentSoft,
  },
  positionDivider: {
    height: StyleSheet.hairlineWidth,
    marginHorizontal: Spacing.md,
    backgroundColor: Colors.border,
  },
  positionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 9,
    paddingVertical: 8,
    minHeight: 54,
  },
  collapseAction: {
    width: 34,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  card: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  cardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: 13,
  },
  pressed: { backgroundColor: Colors.surface },
  coinFallback: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mid: { flex: 1, marginLeft: Spacing.md, paddingRight: Spacing.sm, gap: 3 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  symbol: { fontSize: 16, fontWeight: '600', color: Colors.text },
  sub: { fontSize: 13, color: Colors.textMuted },
  sideBadge: { paddingHorizontal: 6, paddingVertical: 1, borderRadius: Radius.sm },
  xyzBadge: { backgroundColor: Colors.surfaceAlt, paddingHorizontal: 5, paddingVertical: 1, borderRadius: Radius.sm },
  right: { alignItems: 'flex-end', marginLeft: Spacing.sm, gap: 2 },
  pnl: { fontSize: 16, fontWeight: '600' },
  roe: { fontSize: 13, fontWeight: '500' },
  spotValue: { fontSize: 16, fontWeight: '600', color: Colors.text, marginLeft: Spacing.sm },
  spotLiability: { color: Colors.down },
  chevron: { marginLeft: Spacing.sm },
  quickActions: {
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.sm,
  },
  quickAction: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    minHeight: 38,
    paddingHorizontal: 5,
    paddingVertical: Spacing.sm,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.075)',
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  quickActionText: { fontSize: 13, lineHeight: 17, fontWeight: '600', textAlign: 'center' },

  // Expanded detail
  detail: { paddingHorizontal: Spacing.lg, paddingBottom: Spacing.md, gap: Spacing.md },
  gridRow: { flexDirection: 'row', gap: Spacing.sm },
  cell: { flex: 1, minWidth: 0, gap: 3 },
  spotDetail: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.xs, paddingBottom: Spacing.md },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  cellValue: { marginTop: 1, fontSize: 15, lineHeight: 20, fontWeight: '600' },
  cellValueRow: { flexDirection: 'row', alignItems: 'center', gap: 5, minHeight: 27 },
  actionBtnPressed: { backgroundColor: Colors.surfacePress },
  cancelBtn: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    borderRadius: Radius.md,
    backgroundColor: Colors.surfaceAlt,
    marginLeft: Spacing.sm,
  },
  chartLink: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 2, paddingTop: Spacing.xs },

  portfolioWrap: { paddingHorizontal: Spacing.lg },
  disclaimer: { textAlign: 'center', marginTop: Spacing.lg },
});
