import { Colors, Radius, Spacing } from '@/constants/theme';
import { Platform, StyleSheet } from 'react-native';

export const GLASS_FILL = Colors.surfaceAlt;
export const GLASS_FILL_STRONG = Colors.surfacePress;
export const GLASS_INSET = Colors.background;
export const GLASS_HAIRLINE = Colors.border;

export const styles = StyleSheet.create({
  backdrop: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: '#000000C2' },
  sheetWrap: { flex: 1, justifyContent: 'flex-end' },
  sheetMotion: { height: '92%' },
  sheet: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: GLASS_HAIRLINE,
    overflow: 'hidden',
    padding: Spacing.lg,
    paddingBottom: Spacing.xxl,
    gap: Spacing.md,
    // A definite height lets the flexing ScrollView yield space to the fixed
    // review dock. `maxHeight` alone can leave the sheet intrinsically sized and
    // clip the dock when a longer sizing mode is selected.
    flex: 1,
  },
  sheetFallback: { backgroundColor: Colors.surface },
  // Give the scrolling body a bounded flex area so the review dock remains pinned
  // even when a sizing mode (notably Risk) adds more fields than fit on screen.
  ticketContent: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minHeight: 0,
    overflow: 'hidden',
    gap: Spacing.md,
  },
  body: { flexGrow: 1, flexShrink: 1, flexBasis: 0, minHeight: 0 },
  bodyContent: { gap: 14, paddingBottom: Spacing.sm },
  sheetDragHeader: { gap: Spacing.md },
  handle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: GLASS_FILL_STRONG,
    marginBottom: Spacing.xs,
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  levBadge: { backgroundColor: GLASS_FILL_STRONG, paddingHorizontal: 8, paddingVertical: 3, borderRadius: Radius.sm },

  tradeControlRow: { flexDirection: 'row', gap: Spacing.sm },
  tradeControl: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GLASS_HAIRLINE,
    backgroundColor: GLASS_FILL,
  },

  closeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: GLASS_FILL,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  sideRow: {
    flexDirection: 'row',
    gap: 4,
    padding: 4,
    borderRadius: Radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GLASS_HAIRLINE,
    backgroundColor: GLASS_INSET,
  },
  sideBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  availableRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },

  segment: { flexDirection: 'row', backgroundColor: GLASS_INSET, borderRadius: Radius.sm, padding: 3, gap: 3 },
  segmentItem: { flex: 1, alignItems: 'center', paddingVertical: Spacing.sm, borderRadius: Radius.sm },
  segmentItemActive: { backgroundColor: GLASS_FILL_STRONG },

  safetyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.md,
    backgroundColor: GLASS_FILL,
    borderRadius: Radius.md,
  },
  safetyCopy: { flex: 1 },
  switchTrack: {
    width: 42,
    height: 24,
    borderRadius: Radius.pill,
    backgroundColor: GLASS_INSET,
    padding: 2,
    justifyContent: 'center',
  },
  switchTrackOn: { backgroundColor: Colors.accent },
  switchThumb: { width: 20, height: 20, borderRadius: 10, backgroundColor: Colors.textMuted },
  switchThumbOn: { alignSelf: 'flex-end', backgroundColor: '#FFFFFF' },

  advancedCard: {
    backgroundColor: GLASS_FILL,
    borderRadius: Radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GLASS_HAIRLINE,
    overflow: 'hidden',
  },
  advancedHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.md,
  },
  advancedBody: {
    gap: Spacing.sm,
    padding: Spacing.md,
    paddingTop: Spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: GLASS_HAIRLINE,
  },
  safeFallback: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    padding: Spacing.sm,
    borderRadius: Radius.sm,
    backgroundColor: Colors.warning + '12',
  },

  levCard: { backgroundColor: GLASS_FILL, borderRadius: Radius.md, padding: Spacing.md, gap: Spacing.sm },
  levRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  levDivider: { height: StyleSheet.hairlineWidth, backgroundColor: GLASS_HAIRLINE },
  marginToggle: { flexDirection: 'row', backgroundColor: GLASS_INSET, borderRadius: Radius.sm, padding: 2, gap: 2 },
  marginBtn: { paddingHorizontal: Spacing.md, paddingVertical: 5, borderRadius: Radius.sm },
  marginBtnOn: { backgroundColor: GLASS_FILL_STRONG },
  riskUnitBtn: { minWidth: 34, alignItems: 'center', paddingHorizontal: Spacing.sm, paddingVertical: 5, borderRadius: Radius.sm },
  chipRow: { flexDirection: 'row', gap: Spacing.sm, flexWrap: 'wrap' },
  chip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: Radius.pill,
    backgroundColor: GLASS_FILL,
    borderWidth: 1,
    borderColor: GLASS_HAIRLINE,
    minWidth: 46,
    alignItems: 'center',
  },
  chipOn: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  slippageInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: GLASS_INSET,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm,
  },
  slippageInput: {
    minWidth: 52,
    color: Colors.text,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
    paddingVertical: 6,
  },

  field: {
    backgroundColor: GLASS_INSET,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: GLASS_HAIRLINE,
    padding: Spacing.md,
    gap: 4,
  },
  fieldHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  inputRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm },
  // App font (SF Pro) with tabular figures — matches the rest of the app; no monospace.
  input: { flex: 1, color: Colors.text, fontSize: 22, fontWeight: '600', fontVariant: ['tabular-nums'], paddingVertical: 2 },
  modeSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
    borderRadius: Radius.sm,
    backgroundColor: GLASS_FILL,
  },
  midButton: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
    borderRadius: Radius.sm,
    backgroundColor: Colors.accent + '14',
  },
  modeToggle: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  convertLine: { marginTop: -Spacing.xs, marginLeft: Spacing.xs },

  allocationRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  allocationTrackTouch: { flex: 1, minHeight: 48, justifyContent: 'center' },
  allocationTrack: {
    height: 8,
    borderRadius: Radius.pill,
    backgroundColor: GLASS_FILL_STRONG,
  },
  allocationFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: Radius.pill,
    backgroundColor: Colors.accent + '88',
  },
  allocationDot: {
    position: 'absolute',
    top: -2,
    width: 12,
    height: 12,
    marginLeft: -6,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.24)',
  },
  allocationDotOn: { backgroundColor: Colors.accent },
  allocationThumb: {
    position: 'absolute',
    top: -7,
    width: 22,
    height: 22,
    marginLeft: -11,
    borderRadius: 11,
    borderWidth: 3,
    borderColor: Colors.accent,
    backgroundColor: '#07090D',
  },
  allocationInputWrap: {
    width: 92,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 5,
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: GLASS_HAIRLINE,
    backgroundColor: GLASS_INSET,
  },
  allocationInput: {
    minWidth: 42,
    color: Colors.text,
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
    paddingVertical: 4,
  },

  optionList: { gap: Spacing.sm },
  optionRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, minHeight: 34 },
  checkbox: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: GLASS_FILL_STRONG,
    backgroundColor: GLASS_INSET,
  },
  checkboxOn: { borderColor: Colors.accent, backgroundColor: Colors.accent },

  pctRow: { flexDirection: 'row', gap: Spacing.sm },
  pctChip: { flex: 1, alignItems: 'center', paddingVertical: Spacing.sm, borderRadius: Radius.sm, backgroundColor: GLASS_FILL },
  pctChipDisabled: { opacity: 0.4 },

  infoCard: {
    backgroundColor: 'rgba(0,0,0,0.14)',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: GLASS_FILL_STRONG,
    paddingTop: Spacing.md,
    gap: Spacing.sm,
  },
  infoRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 22 },
  implicationRow: { gap: 3, paddingTop: Spacing.xs, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: GLASS_HAIRLINE },
  implicationValue: { flexShrink: 1 },

  tpslCard: {
    backgroundColor: GLASS_FILL,
    borderRadius: Radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GLASS_HAIRLINE,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  tpslHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  tpslRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: GLASS_INSET,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Platform.OS === 'ios' ? Spacing.sm : 4,
  },
  tpslDot: { width: 8, height: 8, borderRadius: 4 },
  riskSummaryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  tpslInput: {
    flex: 1,
    color: Colors.text,
    fontSize: 16,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
    paddingVertical: 4,
  },

  hint: { marginTop: Spacing.xs },
  submitDock: {
    flexShrink: 0,
    gap: Spacing.sm,
    paddingTop: Spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: GLASS_HAIRLINE,
  },
  submitSummary: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  submitSummaryRight: { alignItems: 'flex-end' },
  stopDisclaimer: { textAlign: 'center' },
  submit: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    minHeight: 52,
  },
  submitBusy: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm },

  accessory: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    backgroundColor: 'transparent',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: GLASS_HAIRLINE,
  },
  steppers: { flexDirection: 'row', alignItems: 'center', backgroundColor: GLASS_FILL, borderRadius: Radius.sm, overflow: 'hidden' },
  stepBtn: { paddingHorizontal: Spacing.lg, paddingVertical: 7 },
  stepDivider: { width: StyleSheet.hairlineWidth, alignSelf: 'stretch', backgroundColor: GLASS_HAIRLINE },
  doneBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.md,
    paddingVertical: 7,
    borderRadius: Radius.sm,
    backgroundColor: Colors.accentSoft,
  },

  result: { alignItems: 'center', gap: Spacing.sm, paddingVertical: Spacing.lg },
  resultLegs: {
    alignSelf: 'stretch',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.md,
    backgroundColor: GLASS_FILL,
  },
  resultLegRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  resultLegCopy: { flex: 1 },
  resultBtns: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.md, alignSelf: 'stretch' },
  resultBtn: { flex: 1, alignItems: 'center', paddingVertical: Spacing.md, borderRadius: Radius.md },
  resultBtnGhost: { backgroundColor: GLASS_FILL },
});
